services:
  whisper-stt:
    build:
      context: ./Whisper-STT
    ports:
      - "5002:5001"
    container_name: whisper-stt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  vectordb:
    build:
      context: ./VectorDB
    ports:
      - "5001:5001"
    container_name: vector-db

  phi4:
    build:
      context: ./phi4
    ports:
      - "6000:6000"
    container_name: phi4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phi4
      - whisper-stt
      - vectordb