# Base image with Python 3.9 and CUDA support
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Install Python and dependencies
RUN apt-get update && apt-get install -y \
    python3 python3-pip ffmpeg build-essential python3-dev tzdata \
    && rm -rf /var/lib/apt/lists/*

# Set Python3 as default
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set working directory
WORKDIR /app

# Copy requirements file and install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy Gunicorn configuration
COPY gunicorn_config.py /app

# Copy the script to calculate workers
COPY calculate_workers.py /app

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 5001

# Set the entrypoint to use Gunicorn with dynamic workers
CMD ["sh", "-c", "gunicorn -c gunicorn_config.py --workers $(python3 calculate_workers.py) stt_service:app"]
