# Base image with Python 3.9 and CUDA support
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Install Python and dependencies
RUN apt-get update && apt-get install -y \
    python3 python3-pip ffmpeg build-essential python3-dev tzdata \
    && rm -rf /var/lib/apt/lists/*

# Set Python3 as default
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set working directory
WORKDIR /app

# Install Python dependencies
RUN pip install flask openai-whisper numpy scipy \
    && pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 -f https://download.pytorch.org/whl/torch_stable.html \
    && pip install gunicorn

# Copy application code
COPY . .

# Copy Gunicorn configuration
COPY gunicorn_config.py /app

# Expose the application port
EXPOSE 5001

# Run the app with Gunicorn
CMD ["gunicorn", "-c", "gunicorn_config.py", "stt_service:app"]
