# Base image with Python 3.9
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Install system dependencies with unattended configuration
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    ffmpeg \
    build-essential \
    python3-dev \
    tzdata \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Install Whisper
RUN pip install openai-whisper

# Copy the app
COPY . .

# Expose the app port
EXPOSE 5001

# Run the app
CMD ["python", "stt_service.py"]
