FROM python:3.9-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy requirements file and install Python dependencies
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Copy Gunicorn configuration
COPY gunicorn_config.py /app

# Copy the script to calculate workers
COPY calculate_workers.py /app

# Copy the application code
COPY . /app

# Expose the database port
EXPOSE 5001

# Set the entrypoint to use Gunicorn with dynamic workers
CMD ["sh", "-c", "gunicorn -c gunicorn_config.py --workers $(python3 calculate_workers.py) vector_db_service:app"]