FROM python:3.9-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install FAISS, Flask, and Gunicorn
RUN pip3 install faiss-cpu flask gunicorn

# Set the working directory
WORKDIR /app

# Copy the application code
COPY . /app

# Expose the database port
EXPOSE 5001

# Copy the script to calculate workers
COPY calculate_workers.py /app

# Set the entrypoint to use Gunicorn with dynamic workers
CMD ["sh", "-c", "gunicorn -c gunicorn_config.py --workers $(python3 calculate_workers.py) vector_db_service:app"]